apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-deploy-hpa-memory
  namespace: default
spec:
  scaleTargetRef:
	apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
	resource: 
	  name: memory
	  target:
		type: Utilization
		averagevalue: 400M